export const TRANSACTION_SERVICE_URLS: Record<string, string> = {
  '1': 'https://safe-transaction-mainnet.safe.global/api',
  '10': 'https://safe-transaction-optimism.safe.global/api',
  '56': 'https://safe-transaction-bsc.safe.global/api',
  '100': 'https://safe-transaction-gnosis-chain.safe.global/api',
  '137': 'https://safe-transaction-polygon.safe.global/api',
  '196': 'https://safe-transaction-xlayer.safe.global/api',
  '324': 'https://safe-transaction-zksync.safe.global/api',
  '1101': 'https://safe-transaction-zkevm.safe.global/api',
  '5000': 'https://safe-transaction-mantle.safe.global/api',
  '8453': 'https://safe-transaction-base.safe.global/api',
  '42161': 'https://safe-transaction-arbitrum.safe.global/api',
  '42220': 'https://safe-transaction-celo.safe.global/api',
  '43114': 'https://safe-transaction-avalanche.safe.global/api',
  '59144': 'https://safe-transaction-linea.safe.global/api',
  '81457': 'https://safe-transaction-blast.safe.global/api',
  '84532': 'https://safe-transaction-base-sepolia.safe.global/api',
  '534352': 'https://safe-transaction-scroll.safe.global/api',
  '11155111': 'https://safe-transaction-sepolia.safe.global/api',
  '1313161554': 'https://safe-transaction-aurora.safe.global/api'
}
