name: Create publish info file

on:
  release:
    types: [created]
  workflow_dispatch:
  push:
    branches:
      - prepare-release

permissions:
  contents: read

jobs:
  generate-publish-info:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Run integrity check script
        run: |
          yarn generate-publish-info

      - name: Upload YAML artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: publish-info
          path: ./publish-info

      - name: Show YAML output
        run: cat ./publish-info/*.yml
