name: e2e Test
on:
  pull_request:
  push:
    branches:
      - main
      - development
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: |
          yarn install --frozen-lockfile
          yarn build
          yarn test:ci
