name: Integrity check

on:
  release:
    types: [created]
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - prepare-release

jobs:
  integrity-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Run integrity check script
        run: |
          ts-node ./scripts/integrity-check.ts

      - name: Upload YAML artifact
        uses: actions/upload-artifact@v3
        with:
          name: package-validation-details
          path: ./publish-info.yaml

      - name: Show YAML output
        run: cat ./publish-info.yaml
