name: Protocol Kit - E2E Tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - development

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/development' }}

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        provider: [ethers, viem]
        contract-version: [v1.0.0, v1.1.1, v1.2.0, v1.3.0, v1.4.1, v1.5.0]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271  # v6.0.9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: |
          pnpm install --frozen-lockfile
          pnpm build
      - name: Test ${{ matrix.provider }} - Safe ${{ matrix.contract-version }}
        run: |
          cd packages/protocol-kit
          pnpm test:hardhat:${{ matrix.provider }}:${{ matrix.contract-version }}
