name: Monorepo Test
on:
  pull_request:
  push:
    branches:
      - main
      - development
env:
  INFURA_KEY: ${{ secrets.INFURA_KEY }}
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Yarn cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn install
        run: |
          mkdir .yarncache
          yarn install --cache-folder ./.yarncache --frozen-lockfile
          rm -rf .yarncache
          yarn cache clean

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Account Abstraction Kit coverage
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: packages/account-abstraction-kit
          file: packages/account-abstraction-kit/coverage/lcov.info

      - name: Auth Kit coverage
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: packages/auth-kit
          file: packages/auth-kit/coverage/lcov.info

      - name: OnRamp Kit coverage
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: packages/onramp-kit
          file: packages/onramp-kit/coverage/lcov.info

      - name: Relay Kit coverage
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: packages/relay-kit
          file: packages/relay-kit/coverage/lcov.info

      - name: Api Kit coverage
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: packages/api-kit
          file: packages/api-kit/coverage/lcov.info
