name: Safe Core SDK Test - Contracts
on:
  pull_request:
  push:
    branches:
      - main
      - development
env:
  INFURA_KEY: ${{ secrets.INFURA_KEY }}
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        provider: [ethers, web3]
        contract-version: [v1.0.0, v1.1.1, v1.2.0, v1.3.0, v1.4.1]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: |
          yarn install --frozen-lockfile
          yarn build
      - name: Test ${{ matrix.provider }} - Safe ${{ matrix.contract-version }}
        run: |
          cd packages/protocol-kit
          yarn test:hardhat:${{ matrix.provider }}:${{ matrix.contract-version }}
