name: typedoc

on:
  push:
    branches:
      - main

jobs:
  typedoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          yarn install
          yarn build

      - run: yarn add -W -D typescript typedoc

      - name: Create the docs directory locally in CI
        run: ./node_modules/.bin/typedoc --tsconfig packages/protocol-kit/tsconfig.json --readme packages/protocol-kit/README.md packages/protocol-kit/src

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.4.1
        with:
          branch: gh-pages
          folder: docs
