name: typedoc


on:
  push:
    branches:
      - main

jobs:
  typedoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - run: npm install

      - run: npm run build

      - run: npm install typescript typedoc

      - name: Create the docs directory locally in CI
        run: ./node_modules/.bin/typedoc --tsconfig packages/safe-core-sdk/tsconfig.json packages/safe-core-sdk/src

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
